/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SidebarRouteRouteImport } from './../routes/_sidebar/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as SidebarRunsHistoryRouteImport } from './../routes/_sidebar/runs-history'
import { Route as SidebarRunsRouteImport } from './../routes/_sidebar/runs'
import { Route as SidebarRulesRouteImport } from './../routes/_sidebar/rules'
import { Route as SidebarProfilerRouteImport } from './../routes/_sidebar/profiler'
import { Route as SidebarProfileRouteImport } from './../routes/_sidebar/profile'
import { Route as SidebarInsightsRouteImport } from './../routes/_sidebar/insights'
import { Route as SidebarHomeRouteImport } from './../routes/_sidebar/home'
import { Route as SidebarDiscoveryRouteImport } from './../routes/_sidebar/discovery'
import { Route as SidebarConfigRouteImport } from './../routes/_sidebar/config'
import { Route as SidebarRunsIndexRouteImport } from './../routes/_sidebar/runs.index'
import { Route as SidebarRulesIndexRouteImport } from './../routes/_sidebar/rules.index'
import { Route as SidebarRunsRunNameRouteImport } from './../routes/_sidebar/runs.$runName'
import { Route as SidebarRulesSingleTableRouteImport } from './../routes/_sidebar/rules.single-table'
import { Route as SidebarRulesImportRouteImport } from './../routes/_sidebar/rules.import'
import { Route as SidebarRulesFromContractRouteImport } from './../routes/_sidebar/rules.from-contract'
import { Route as SidebarRulesDraftsRouteImport } from './../routes/_sidebar/rules.drafts'
import { Route as SidebarRulesCreateSqlRouteImport } from './../routes/_sidebar/rules.create-sql'
import { Route as SidebarRulesCreateReusableRouteImport } from './../routes/_sidebar/rules.create-reusable'
import { Route as SidebarRulesCreateRouteImport } from './../routes/_sidebar/rules.create'
import { Route as SidebarRulesActiveRouteImport } from './../routes/_sidebar/rules.active'

const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarRunsHistoryRoute = SidebarRunsHistoryRouteImport.update({
  id: '/runs-history',
  path: '/runs-history',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarRunsRoute = SidebarRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarRulesRoute = SidebarRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarProfilerRoute = SidebarProfilerRouteImport.update({
  id: '/profiler',
  path: '/profiler',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarProfileRoute = SidebarProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarInsightsRoute = SidebarInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarHomeRoute = SidebarHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarDiscoveryRoute = SidebarDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarConfigRoute = SidebarConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarRunsIndexRoute = SidebarRunsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarRunsRoute,
} as any)
const SidebarRulesIndexRoute = SidebarRulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarRulesRoute,
} as any)
const SidebarRunsRunNameRoute = SidebarRunsRunNameRouteImport.update({
  id: '/$runName',
  path: '/$runName',
  getParentRoute: () => SidebarRunsRoute,
} as any)
const SidebarRulesSingleTableRoute = SidebarRulesSingleTableRouteImport.update({
  id: '/single-table',
  path: '/single-table',
  getParentRoute: () => SidebarRulesRoute,
} as any)
const SidebarRulesImportRoute = SidebarRulesImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => SidebarRulesRoute,
} as any)
const SidebarRulesFromContractRoute =
  SidebarRulesFromContractRouteImport.update({
    id: '/from-contract',
    path: '/from-contract',
    getParentRoute: () => SidebarRulesRoute,
  } as any)
const SidebarRulesDraftsRoute = SidebarRulesDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => SidebarRulesRoute,
} as any)
const SidebarRulesCreateSqlRoute = SidebarRulesCreateSqlRouteImport.update({
  id: '/create-sql',
  path: '/create-sql',
  getParentRoute: () => SidebarRulesRoute,
} as any)
const SidebarRulesCreateReusableRoute =
  SidebarRulesCreateReusableRouteImport.update({
    id: '/create-reusable',
    path: '/create-reusable',
    getParentRoute: () => SidebarRulesRoute,
  } as any)
const SidebarRulesCreateRoute = SidebarRulesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => SidebarRulesRoute,
} as any)
const SidebarRulesActiveRoute = SidebarRulesActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => SidebarRulesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config': typeof SidebarConfigRoute
  '/discovery': typeof SidebarDiscoveryRoute
  '/home': typeof SidebarHomeRoute
  '/insights': typeof SidebarInsightsRoute
  '/profile': typeof SidebarProfileRoute
  '/profiler': typeof SidebarProfilerRoute
  '/rules': typeof SidebarRulesRouteWithChildren
  '/runs': typeof SidebarRunsRouteWithChildren
  '/runs-history': typeof SidebarRunsHistoryRoute
  '/rules/active': typeof SidebarRulesActiveRoute
  '/rules/create': typeof SidebarRulesCreateRoute
  '/rules/create-reusable': typeof SidebarRulesCreateReusableRoute
  '/rules/create-sql': typeof SidebarRulesCreateSqlRoute
  '/rules/drafts': typeof SidebarRulesDraftsRoute
  '/rules/from-contract': typeof SidebarRulesFromContractRoute
  '/rules/import': typeof SidebarRulesImportRoute
  '/rules/single-table': typeof SidebarRulesSingleTableRoute
  '/runs/$runName': typeof SidebarRunsRunNameRoute
  '/rules/': typeof SidebarRulesIndexRoute
  '/runs/': typeof SidebarRunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config': typeof SidebarConfigRoute
  '/discovery': typeof SidebarDiscoveryRoute
  '/home': typeof SidebarHomeRoute
  '/insights': typeof SidebarInsightsRoute
  '/profile': typeof SidebarProfileRoute
  '/profiler': typeof SidebarProfilerRoute
  '/runs-history': typeof SidebarRunsHistoryRoute
  '/rules/active': typeof SidebarRulesActiveRoute
  '/rules/create': typeof SidebarRulesCreateRoute
  '/rules/create-reusable': typeof SidebarRulesCreateReusableRoute
  '/rules/create-sql': typeof SidebarRulesCreateSqlRoute
  '/rules/drafts': typeof SidebarRulesDraftsRoute
  '/rules/from-contract': typeof SidebarRulesFromContractRoute
  '/rules/import': typeof SidebarRulesImportRoute
  '/rules/single-table': typeof SidebarRulesSingleTableRoute
  '/runs/$runName': typeof SidebarRunsRunNameRoute
  '/rules': typeof SidebarRulesIndexRoute
  '/runs': typeof SidebarRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/_sidebar/config': typeof SidebarConfigRoute
  '/_sidebar/discovery': typeof SidebarDiscoveryRoute
  '/_sidebar/home': typeof SidebarHomeRoute
  '/_sidebar/insights': typeof SidebarInsightsRoute
  '/_sidebar/profile': typeof SidebarProfileRoute
  '/_sidebar/profiler': typeof SidebarProfilerRoute
  '/_sidebar/rules': typeof SidebarRulesRouteWithChildren
  '/_sidebar/runs': typeof SidebarRunsRouteWithChildren
  '/_sidebar/runs-history': typeof SidebarRunsHistoryRoute
  '/_sidebar/rules/active': typeof SidebarRulesActiveRoute
  '/_sidebar/rules/create': typeof SidebarRulesCreateRoute
  '/_sidebar/rules/create-reusable': typeof SidebarRulesCreateReusableRoute
  '/_sidebar/rules/create-sql': typeof SidebarRulesCreateSqlRoute
  '/_sidebar/rules/drafts': typeof SidebarRulesDraftsRoute
  '/_sidebar/rules/from-contract': typeof SidebarRulesFromContractRoute
  '/_sidebar/rules/import': typeof SidebarRulesImportRoute
  '/_sidebar/rules/single-table': typeof SidebarRulesSingleTableRoute
  '/_sidebar/runs/$runName': typeof SidebarRunsRunNameRoute
  '/_sidebar/rules/': typeof SidebarRulesIndexRoute
  '/_sidebar/runs/': typeof SidebarRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config'
    | '/discovery'
    | '/home'
    | '/insights'
    | '/profile'
    | '/profiler'
    | '/rules'
    | '/runs'
    | '/runs-history'
    | '/rules/active'
    | '/rules/create'
    | '/rules/create-reusable'
    | '/rules/create-sql'
    | '/rules/drafts'
    | '/rules/from-contract'
    | '/rules/import'
    | '/rules/single-table'
    | '/runs/$runName'
    | '/rules/'
    | '/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/config'
    | '/discovery'
    | '/home'
    | '/insights'
    | '/profile'
    | '/profiler'
    | '/runs-history'
    | '/rules/active'
    | '/rules/create'
    | '/rules/create-reusable'
    | '/rules/create-sql'
    | '/rules/drafts'
    | '/rules/from-contract'
    | '/rules/import'
    | '/rules/single-table'
    | '/runs/$runName'
    | '/rules'
    | '/runs'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/_sidebar/config'
    | '/_sidebar/discovery'
    | '/_sidebar/home'
    | '/_sidebar/insights'
    | '/_sidebar/profile'
    | '/_sidebar/profiler'
    | '/_sidebar/rules'
    | '/_sidebar/runs'
    | '/_sidebar/runs-history'
    | '/_sidebar/rules/active'
    | '/_sidebar/rules/create'
    | '/_sidebar/rules/create-reusable'
    | '/_sidebar/rules/create-sql'
    | '/_sidebar/rules/drafts'
    | '/_sidebar/rules/from-contract'
    | '/_sidebar/rules/import'
    | '/_sidebar/rules/single-table'
    | '/_sidebar/runs/$runName'
    | '/_sidebar/rules/'
    | '/_sidebar/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/runs-history': {
      id: '/_sidebar/runs-history'
      path: '/runs-history'
      fullPath: '/runs-history'
      preLoaderRoute: typeof SidebarRunsHistoryRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/runs': {
      id: '/_sidebar/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof SidebarRunsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/rules': {
      id: '/_sidebar/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof SidebarRulesRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/profiler': {
      id: '/_sidebar/profiler'
      path: '/profiler'
      fullPath: '/profiler'
      preLoaderRoute: typeof SidebarProfilerRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/profile': {
      id: '/_sidebar/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SidebarProfileRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/insights': {
      id: '/_sidebar/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof SidebarInsightsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/home': {
      id: '/_sidebar/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof SidebarHomeRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/discovery': {
      id: '/_sidebar/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof SidebarDiscoveryRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/config': {
      id: '/_sidebar/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof SidebarConfigRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/runs/': {
      id: '/_sidebar/runs/'
      path: '/'
      fullPath: '/runs/'
      preLoaderRoute: typeof SidebarRunsIndexRouteImport
      parentRoute: typeof SidebarRunsRoute
    }
    '/_sidebar/rules/': {
      id: '/_sidebar/rules/'
      path: '/'
      fullPath: '/rules/'
      preLoaderRoute: typeof SidebarRulesIndexRouteImport
      parentRoute: typeof SidebarRulesRoute
    }
    '/_sidebar/runs/$runName': {
      id: '/_sidebar/runs/$runName'
      path: '/$runName'
      fullPath: '/runs/$runName'
      preLoaderRoute: typeof SidebarRunsRunNameRouteImport
      parentRoute: typeof SidebarRunsRoute
    }
    '/_sidebar/rules/single-table': {
      id: '/_sidebar/rules/single-table'
      path: '/single-table'
      fullPath: '/rules/single-table'
      preLoaderRoute: typeof SidebarRulesSingleTableRouteImport
      parentRoute: typeof SidebarRulesRoute
    }
    '/_sidebar/rules/import': {
      id: '/_sidebar/rules/import'
      path: '/import'
      fullPath: '/rules/import'
      preLoaderRoute: typeof SidebarRulesImportRouteImport
      parentRoute: typeof SidebarRulesRoute
    }
    '/_sidebar/rules/from-contract': {
      id: '/_sidebar/rules/from-contract'
      path: '/from-contract'
      fullPath: '/rules/from-contract'
      preLoaderRoute: typeof SidebarRulesFromContractRouteImport
      parentRoute: typeof SidebarRulesRoute
    }
    '/_sidebar/rules/drafts': {
      id: '/_sidebar/rules/drafts'
      path: '/drafts'
      fullPath: '/rules/drafts'
      preLoaderRoute: typeof SidebarRulesDraftsRouteImport
      parentRoute: typeof SidebarRulesRoute
    }
    '/_sidebar/rules/create-sql': {
      id: '/_sidebar/rules/create-sql'
      path: '/create-sql'
      fullPath: '/rules/create-sql'
      preLoaderRoute: typeof SidebarRulesCreateSqlRouteImport
      parentRoute: typeof SidebarRulesRoute
    }
    '/_sidebar/rules/create-reusable': {
      id: '/_sidebar/rules/create-reusable'
      path: '/create-reusable'
      fullPath: '/rules/create-reusable'
      preLoaderRoute: typeof SidebarRulesCreateReusableRouteImport
      parentRoute: typeof SidebarRulesRoute
    }
    '/_sidebar/rules/create': {
      id: '/_sidebar/rules/create'
      path: '/create'
      fullPath: '/rules/create'
      preLoaderRoute: typeof SidebarRulesCreateRouteImport
      parentRoute: typeof SidebarRulesRoute
    }
    '/_sidebar/rules/active': {
      id: '/_sidebar/rules/active'
      path: '/active'
      fullPath: '/rules/active'
      preLoaderRoute: typeof SidebarRulesActiveRouteImport
      parentRoute: typeof SidebarRulesRoute
    }
  }
}

interface SidebarRulesRouteChildren {
  SidebarRulesActiveRoute: typeof SidebarRulesActiveRoute
  SidebarRulesCreateRoute: typeof SidebarRulesCreateRoute
  SidebarRulesCreateReusableRoute: typeof SidebarRulesCreateReusableRoute
  SidebarRulesCreateSqlRoute: typeof SidebarRulesCreateSqlRoute
  SidebarRulesDraftsRoute: typeof SidebarRulesDraftsRoute
  SidebarRulesFromContractRoute: typeof SidebarRulesFromContractRoute
  SidebarRulesImportRoute: typeof SidebarRulesImportRoute
  SidebarRulesSingleTableRoute: typeof SidebarRulesSingleTableRoute
  SidebarRulesIndexRoute: typeof SidebarRulesIndexRoute
}

const SidebarRulesRouteChildren: SidebarRulesRouteChildren = {
  SidebarRulesActiveRoute: SidebarRulesActiveRoute,
  SidebarRulesCreateRoute: SidebarRulesCreateRoute,
  SidebarRulesCreateReusableRoute: SidebarRulesCreateReusableRoute,
  SidebarRulesCreateSqlRoute: SidebarRulesCreateSqlRoute,
  SidebarRulesDraftsRoute: SidebarRulesDraftsRoute,
  SidebarRulesFromContractRoute: SidebarRulesFromContractRoute,
  SidebarRulesImportRoute: SidebarRulesImportRoute,
  SidebarRulesSingleTableRoute: SidebarRulesSingleTableRoute,
  SidebarRulesIndexRoute: SidebarRulesIndexRoute,
}

const SidebarRulesRouteWithChildren = SidebarRulesRoute._addFileChildren(
  SidebarRulesRouteChildren,
)

interface SidebarRunsRouteChildren {
  SidebarRunsRunNameRoute: typeof SidebarRunsRunNameRoute
  SidebarRunsIndexRoute: typeof SidebarRunsIndexRoute
}

const SidebarRunsRouteChildren: SidebarRunsRouteChildren = {
  SidebarRunsRunNameRoute: SidebarRunsRunNameRoute,
  SidebarRunsIndexRoute: SidebarRunsIndexRoute,
}

const SidebarRunsRouteWithChildren = SidebarRunsRoute._addFileChildren(
  SidebarRunsRouteChildren,
)

interface SidebarRouteRouteChildren {
  SidebarConfigRoute: typeof SidebarConfigRoute
  SidebarDiscoveryRoute: typeof SidebarDiscoveryRoute
  SidebarHomeRoute: typeof SidebarHomeRoute
  SidebarInsightsRoute: typeof SidebarInsightsRoute
  SidebarProfileRoute: typeof SidebarProfileRoute
  SidebarProfilerRoute: typeof SidebarProfilerRoute
  SidebarRulesRoute: typeof SidebarRulesRouteWithChildren
  SidebarRunsRoute: typeof SidebarRunsRouteWithChildren
  SidebarRunsHistoryRoute: typeof SidebarRunsHistoryRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarConfigRoute: SidebarConfigRoute,
  SidebarDiscoveryRoute: SidebarDiscoveryRoute,
  SidebarHomeRoute: SidebarHomeRoute,
  SidebarInsightsRoute: SidebarInsightsRoute,
  SidebarProfileRoute: SidebarProfileRoute,
  SidebarProfilerRoute: SidebarProfilerRoute,
  SidebarRulesRoute: SidebarRulesRouteWithChildren,
  SidebarRunsRoute: SidebarRunsRouteWithChildren,
  SidebarRunsHistoryRoute: SidebarRunsHistoryRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
