"""Build the DQX Studio application bundle.

Produces, under ``app/.build/``:

* ``openapi.json`` — FastAPI-derived OpenAPI 3.x schema (input to orval).
* ``app.yml`` — Databricks Apps launch manifest (uvicorn invocation).
* ``requirements.txt`` — pip requirements file listing the app wheel.
* ``databricks_labs_dqx_app-<version>-py3-none-any.whl`` — application
  wheel built with hatchling + uv-dynamic-versioning. The version
  includes a build-tag local-version segment (e.g. ``+abc1234.b20260530t012345``)
  so successive deploys at the same git commit reinstall fresh code in
  Databricks Apps' persistent venv.

Side effects on the source tree:

* ``src/databricks_labs_dqx_app/_metadata.py`` is regenerated from
  ``[tool.dqx_app.metadata]`` in ``pyproject.toml``.
* ``src/databricks_labs_dqx_app/ui/lib/api.ts`` is regenerated by orval
  from the freshly-dumped OpenAPI schema.
* ``src/databricks_labs_dqx_app/__dist__/`` is overwritten by ``vite build``.

The script is invoked from the ``app-build`` Makefile target (and
transitively from the ``databricks.yml`` ``artifacts.default.build``
pipeline). Designed to be cwd-independent — paths are resolved relative
to this file's location.
"""

from __future__ import annotations

import json
import os
import subprocess
import time
import tomllib
from pathlib import Path

APP_DIR = Path(__file__).resolve().parent.parent  # scripts/build_app.py → app/
PYPROJECT = APP_DIR / "pyproject.toml"
BUILD_DIR = APP_DIR / ".build"
NODE_BIN = APP_DIR / "node_modules" / ".bin"

PKG_DIR = APP_DIR / "src" / "databricks_labs_dqx_app"
METADATA_PY = PKG_DIR / "_metadata.py"
API_TS = PKG_DIR / "ui" / "lib" / "api.ts"
DIST_DIR = PKG_DIR / "__dist__"


def _step(msg: str) -> None:
    print(f"\n▶ {msg}", flush=True)


def _run(cmd: list[str], env: dict[str, str] | None = None) -> None:
    """Run a subprocess from ``APP_DIR`` with stdio passed through.

    Failures abort the build via ``check=True`` — every stage must
    succeed for the wheel to be considered usable.
    """
    print(f"  $ {' '.join(cmd)}", flush=True)
    subprocess.run(cmd, cwd=APP_DIR, check=True, env=env)  # noqa: S603


def _read_app_metadata() -> dict[str, str]:
    """Return ``[tool.dqx_app.metadata]`` from ``pyproject.toml``.

    Single source of truth for app identity. ``vite.config.ts`` reads
    the same key — keeping the two consumers in lockstep on schema
    changes is intentional (rename here ⇒ rename there).
    """
    with PYPROJECT.open("rb") as f:
        pyproject = tomllib.load(f)
    meta = pyproject.get("tool", {}).get("dqx_app", {}).get("metadata", {})
    required = {"app-name", "app-slug", "app-module"}
    missing = required - meta.keys()
    if missing:
        raise SystemExit(
            f"error: [tool.dqx_app.metadata] missing keys {sorted(missing)} in {PYPROJECT}",
        )
    return meta


def _write_metadata_module(meta: dict[str, str]) -> None:
    """Mirror ``[tool.dqx_app.metadata]`` into a runtime-importable module.

    ``backend.config`` and ``backend.logger`` import ``app_name`` /
    ``app_slug`` from here; the wheel embeds this file via
    ``[tool.hatch.build.artifacts]``. Generating it on every build
    keeps source-of-truth in ``pyproject.toml`` while still letting
    runtime code do a plain ``from .._metadata import ...``.

    Uses ``json.dumps`` for value formatting because it always emits
    double-quoted strings, matching the existing file's convention and
    keeping the diff clean across repeat builds. ``repr()`` would
    flip to single quotes on values without embedded double-quotes,
    producing nuisance churn in PRs.
    """
    METADATA_PY.write_text(
        f"app_name = {json.dumps(meta['app-name'])}\n"
        f"app_module = {json.dumps(meta['app-module'])}\n"
        f"app_slug = {json.dumps(meta['app-slug'])}\n"
        'api_prefix = "/api"\n',
        encoding="utf-8",
    )


def _write_app_yml(meta: dict[str, str]) -> None:
    """Write the Databricks Apps launch manifest.

    Single-worker uvicorn. The in-process ``SchedulerService`` is gated by
    a file lock (``/tmp/.dqx_scheduler.lock``) that only excludes other
    workers in the SAME container, so multi-worker would mean two
    schedulers fighting over each due schedule. The ``app-module`` value
    comes from ``pyproject.toml`` so changing the FastAPI app's import
    path is a one-line edit there. Production DABs deploys override the
    command via ``var.app_config.command`` in ``databricks.yml``; this
    manifest is the fallback for paths that don't go through DABs (e.g.
    direct ``databricks apps`` CLI deploys).
    """
    (BUILD_DIR / "app.yml").write_text(
        f'command: ["uvicorn", "{meta["app-module"]}", "--workers", "1"]\n',
        encoding="utf-8",
    )


def _dump_openapi() -> None:
    """Import the FastAPI app and serialize its OpenAPI schema.

    Runs in a subprocess via ``uv run`` so the schema is dumped with
    exactly the same environment used to install the wheel — same
    pydantic / fastapi versions, same plugin set. Importing the app
    in-process here would risk drift if this script ever ran outside
    a proper ``uv`` invocation.
    """
    target = BUILD_DIR / "openapi.json"
    code = (
        "import json, sys;"
        "from databricks_labs_dqx_app.backend.app import app;"
        f"open({str(target)!r}, 'w').write(json.dumps(app.openapi(), indent=2))"
    )
    _run(["uv", "run", "--exact", "--all-extras", "python", "-c", code])


def _run_orval() -> None:
    """Regenerate ``ui/lib/api.ts`` from ``.build/openapi.json``.

    Config picked up from ``orval.config.ts`` at app root, no CLI
    args needed. Invokes the locally-installed binary directly so the
    pinned ``orval@7.21.0`` is used regardless of which package
    manager (yarn / bun / npm) is on PATH.
    """
    _run([str(NODE_BIN / "orval")])


def _run_vite_build() -> None:
    """Compile the React UI into ``src/databricks_labs_dqx_app/__dist__/``.

    Vite reads ``vite.config.ts``, which sets ``build.outDir`` to the
    package's ``__dist__`` folder so hatchling can pick it up via
    ``[tool.hatch.build.artifacts]``.
    """
    _run([str(NODE_BIN / "vite"), "build"])


def _build_wheel(build_tag: str) -> Path:
    """Produce the application wheel with a uniqueness-forcing version tag.

    The ``DQX_APP_BUILD_TAG`` env var is consumed by ``format-jinja`` in
    ``[tool.uv-dynamic-versioning]`` (see ``pyproject.toml``), so the
    wheel's filename AND internal METADATA both end with
    ``.{build_tag}`` — no post-build dist-info rewrite needed.
    """
    env = os.environ.copy()
    env["DQX_APP_BUILD_TAG"] = build_tag
    print(f"  DQX_APP_BUILD_TAG={build_tag}", flush=True)
    _run(
        ["uv", "build", ".", "--wheel", "--out-dir", str(BUILD_DIR)],
        env=env,
    )

    wheels = sorted(BUILD_DIR.glob("databricks_labs_dqx_app-*.whl"))
    if not wheels:
        raise SystemExit(f"error: no app wheel found in {BUILD_DIR} after uv build")
    # ``uv build`` doesn't clear stale wheels from previous runs, so
    # pick the newest by mtime rather than relying on a single match.
    return max(wheels, key=lambda p: p.stat().st_mtime)


def _write_requirements(app_wheel: Path) -> None:
    """Write ``.build/requirements.txt`` listing the freshly-built app wheel.

    The parent ``databricks_labs_dqx`` library wheel is prepended later
    in the ``databricks.yml`` artifact-build pipeline (it's built by a
    separate ``uv build ../`` step the Makefile orchestrates after
    this script). Keeping that split mirrors the original layout so the
    DABs pipeline doesn't need additional changes when this script
    lands.
    """
    (BUILD_DIR / "requirements.txt").write_text(
        f"{app_wheel.name}\n",
        encoding="utf-8",
    )


def _clean_app_wheels() -> None:
    """Remove stale application wheels before rebuilding.

    Without this, every build leaks a new file into ``.build/`` and
    ``_build_wheel``'s newest-by-mtime heuristic still works, but the
    directory grows unboundedly across CI runs and the DABs ``sync``
    step ships every old wheel into Databricks Apps. The DQX library
    wheel (``databricks_labs_dqx-*.whl``) is built by a separate
    ``uv build ../`` step, so we explicitly only sweep the app wheels.
    """
    for stale in BUILD_DIR.glob("databricks_labs_dqx_app-*.whl"):
        stale.unlink()


def main() -> int:
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    _clean_app_wheels()

    meta = _read_app_metadata()

    _step("Writing _metadata.py from pyproject [tool.dqx_app.metadata]")
    _write_metadata_module(meta)

    _step("Writing .build/app.yml")
    _write_app_yml(meta)

    _step("Dumping FastAPI OpenAPI schema → .build/openapi.json")
    _dump_openapi()

    _step("Generating UI API client (orval)")
    _run_orval()

    _step("Building UI bundle (vite build → src/databricks_labs_dqx_app/__dist__/)")
    _run_vite_build()

    # PEP 440 local-version segments must be alphanumeric + dots/hyphens
    # and are case-normalised to lowercase. ``b<timestamp>`` stays human
    # parseable ("b" for build) and sorts monotonically.
    build_tag = time.strftime("b%Y%m%dt%H%M%S")
    _step(f"Building wheel with version tag .{build_tag}")
    app_wheel = _build_wheel(build_tag)

    _step("Writing .build/requirements.txt")
    _write_requirements(app_wheel)

    _step("Build complete:")
    print(f"  → {app_wheel.relative_to(APP_DIR)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
